
package hexclock;

import static hexclock.HexClock.formattedDate;
import java.awt.Color;


public class NewJPanel extends javax.swing.JPanel {

   
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("12:20:14 AM");
        add(jLabel1);
        jLabel1.setBounds(57, 102, 269, 61);
    }// </editor-fold>//GEN-END:initComponents
    public void ChageText(){
        jLabel1.setText(formattedDate);
        jLabel1.setVisible(true);
        jLabel1.setBackground(Color.yellow);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
